# This is a basic workflow to help you get started with Actions

name: Latex

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_1:
    name: Build 1
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Build latex files
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: Skript/main.tex

  build_2:
    name: Build 2
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Build latex files
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: ExerciseSheets/ExerciseSheet1/main.tex
          